### ISSUE TITLE
Installing on Linux Mint 18.1

### ISSUE THREAD

**Issue by mahihossain** [monnerat/insight#12]
I was trying to install Insight debugger on linux mint 18.1. Every time I use *make* it shows following error *Configuring in ./libgui
configure: creating cache ./config.cache
/mnt/28D42DB4D42D8562/Downloads/insight/bundle/libgui/configure: line 2182: syntax error near unexpected token `libgui,'
/mnt/28D42DB4D42D8562/Downloads/insight/bundle/libgui/configure: line 2182: `AM_INIT_AUTOMAKE(libgui, 0.0)'
Makefile:6738: recipe for target 'configure-libgui' failed
make[2]: *** [configure-libgui] Error 1
make[2]: Leaving directory '/mnt/28D42DB4D42D8562/Downloads/insight/bundle'
Makefile:846: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/mnt/28D42DB4D42D8562/Downloads/insight/bundle'
Makefile:4: recipe for target 'notarget' failed
make: *** [notarget] Error 2*

I tried same same with kali linux it worked. But for mint 18.1 it is not working. What might be the problem?

**Comment by monnerat** [comment]
I have no access to a mint, but I can suspect some of the system-wide automake macro files are missing/unreachable.
the word AM_INIT_AUTOMAKE is a macro invocation in libgui/configure.ac that should have been replaced by the macro expansion at configure time. Since it has not been, the macro was probably not available to the configure utility.
Maybe check if a complementary package to automake should be installed ? or maybe a system path problem ?
Also I see you're working on a mounted device: did you already build insight in this same directory on another OS ? If yes, files generated by the previous run may be incompatible with the failing one, so restart from scratch on Mint with a fresh clone.
In any case, I think a Linux Mint guy might be of better advice than me.

**Comment by frederiklikaj** [comment]
hello,
i try to install git clone but i cannot get further than this on my ubuntu 16.04 (64-bit)

# git clone --recursive https://github.com/monnerat/insight.git
Cloning into 'insight'...
remote: Counting objects: 1911, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 1911 (delta 0), reused 0 (delta 0), pack-reused 1909
Receiving objects: 100% (1911/1911), 2.09 MiB | 1.06 MiB/s, done.
Resolving deltas: 100% (1136/1136), done.
Checking connectivity... done.
Submodule 'binutils-gdb' (git://sourceware.org/git/binutils-gdb.git) registered for path 'binutils-gdb'
Cloning into 'binutils-gdb'...
remote: Counting objects: 832359, done.
remote: Compressing objects: 100% (143306/143306), done.
remote: Total 832359 (delta 680661), reused 795586 (delta 677142)
Receiving objects: 100% (832359/832359), 277.57 MiB | 119.00 KiB/s, done.
Resolving deltas: 100% (680661/680661), done.
Checking connectivity... done.
Submodule path 'binutils-gdb': checked out '5e6a0e73317915b0685249606538ea739acc3a23'
/# cd insight.git
-bash: cd: insight.git: Ingen sådan fil eller filkatalog (no such file or filemap)

please help
Thank you in advance

**Comment by monnerat** [comment]
git tells you:

Cloning into 'insight'...

Then why would you assume the created directory is named 'insight.git' ?
"cd insight" would have been more appropriate :-)

For a Ubuntu build, please see http://www.dalfonso.co/2016/04/23/setting-insight-debugger-on-ubuntu-16-04-lts/ for help.

**Comment by monnerat** [comment]
@frederiklikaj: this issue is about "Installing on Linux Mint 18.1" and not about your problem.
You must open a new issue for your case.

**Comment by monnerat** [comment]
I just tried on a Linux Mint 18.1 64-bit VM: Everything is perfect providing:
- dependencies listed at http://www.dalfonso.co/2016/04/23/setting-insight-debugger-on-ubuntu-16-04-lts/, plus g++ and liblzma-dev are installed,
- build is performed on a FRESH clone

Closing the issue.
